# Generated by Django 5.1.2 on 2025-12-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_recipient_read_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_category_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_scheduled_for_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationdeliverylog',
            name='notif_delivery_log_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationdeliverylog',
            name='notif_delivery_retry_idx',
        ),
    ]
