# Generated by Django 5.1.2 on 2025-12-10 15:15

from django.db import migrations


def create_default_customer_preferences(apps, schema_editor):
    """
    Create CustomerNotificationPreference records for all existing customers
    with defaults based on user requirements:
    - notify_pending_approvals: True (default)
    - notify_completions: True (default)
    - notify_new_requests: True (default)
    - All other categories: True (to avoid missing important notifications)
    - Channels: email=True, sms=False, in_app=True
    """
    Customer = apps.get_model('core', 'Customer')
    CustomerNotificationPreference = apps.get_model('core', 'CustomerNotificationPreference')

    customers = Customer.objects.all()
    created_count = 0

    for customer in customers:
        # Check if preference already exists
        if not CustomerNotificationPreference.objects.filter(customer=customer).exists():
            CustomerNotificationPreference.objects.create(
                customer=customer,
                # Global channels
                receive_email_notifications=True,
                receive_sms_notifications=False,  # Opt-in for SMS
                receive_in_app_notifications=True,
                # Customer categories (user-specified defaults)
                notify_pending_approvals=True,
                notify_completions=True,
                notify_new_requests=True,
                # Other categories
                notify_in_progress=True,
                notify_repair_status=True,
                notify_rewards=True,
                notify_system=True,
                # Batch mode
                batch_pending_approvals=False,  # Individual notifications by default
                # Quiet hours disabled by default
                quiet_hours_enabled=False,
            )
            created_count += 1

    if created_count > 0:
        print(f"Created {created_count} CustomerNotificationPreference records")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_notification_notif_recipient_read_created_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_default_customer_preferences,
            reverse_code=migrations.RunPython.noop
        ),
    ]
