# Generated by Django 5.1.2 on 2025-12-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_setup_customer_notification_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When email address was verified', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='When phone number was verified', null=True),
        ),
    ]
