# Generated by Django 5.1.2 on 2026-01-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_customer_portal_notification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Customer ID for billing integration', max_length=100),
        ),
    ]
