# Generated by Django 5.1.2 on 2026-01-28 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('FLEET', 'Fleet Account'), ('RETAIL', 'Individual / Retail'), ('WALK_IN', 'Walk-In')], db_index=True, default='FLEET', help_text='Fleet = business account. Retail = individual person. Walk-in = one-time.', max_length=10),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, db_index=True, help_text="Fleet unit number (e.g., 'Truck #4521'). Primary ID for fleet vehicles.", max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Vehicle model year (e.g., 2024)', null=True)),
                ('make', models.CharField(blank=True, help_text='Vehicle make (e.g., Ford, Peterbilt)', max_length=50)),
                ('model', models.CharField(blank=True, help_text='Vehicle model (e.g., F-150, 389)', max_length=50)),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number (17 characters)', max_length=17)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.customer')),
            ],
            options={
                'ordering': ['customer', 'unit_number', 'make', 'model'],
                'indexes': [models.Index(fields=['customer', 'unit_number'], name='core_vehicl_custome_28952e_idx'), models.Index(fields=['vin'], name='core_vehicl_vin_167573_idx')],
            },
        ),
    ]
