# Generated by Django 5.1.2 on 2026-01-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_expand_data_model'),
        ('tenants', '0001_create_tenant_and_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='tenants.tenant'),
        ),
    ]
