# Generated by Django 5.1.2 on 2026-01-29 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_tenant_fk'),
        ('technician_portal', '0024_add_technician_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='primary_technician',
            field=models.ForeignKey(blank=True, help_text="Default technician assigned to this customer's repairs", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_customers', to='technician_portal.technician'),
        ),
    ]
