# Generated by Django 5.1.2 on 2026-02-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_exempt',
            field=models.BooleanField(default=False, help_text='Customer is exempt from sales tax (government, reseller, etc.)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_exempt_certificate',
            field=models.CharField(blank=True, help_text='Tax exemption certificate number', max_length=100),
        ),
    ]
