# Generated by Django 5.1.2 on 2026-02-10 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customer_tax_exempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdeliverylog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='core.notification'),
        ),
    ]
