# Generated by Django 5.1.2 on 2026-02-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notification_delivery_log_nullable_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='use_progressive_pricing',
            field=models.BooleanField(default=True, help_text='If enabled, repairs get cheaper with each subsequent repair on a unit. If disabled, every repair uses first-repair pricing.'),
        ),
    ]
