# Generated by Django 5.1.2 on 2026-03-14 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seed_repair_notification_templates'),
        ('tenants', '0010_add_grace_period_and_alerts_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdeliverylog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this delivery log (derived from notification recipient)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_delivery_logs', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['tenant', 'created_at'], name='ndl_tenant_created_idx'),
        ),
    ]
