# Generated by Django 5.1.2 on 2026-07-23 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_null_blank_customer_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Flat % off this account's work. Individuals linked to this account inherit it (e.g. 20.00 for 20% off).", max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='parent_account',
            field=models.ForeignKey(blank=True, help_text='Fleet account this individual is linked to, for its discount.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_accounts', to='core.customer'),
        ),
    ]
