# Generated by Django 5.1.2 on 2026-07-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_customer_account_discount_percentage_and_more'),
        ('technician_portal', '0044_backfill_can_replace'),
        ('tenants', '0020_copy_platform_branding_to_owner_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_name_per_tenant',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_type', 'FLEET')), fields=('tenant', 'name'), name='unique_fleet_name_per_tenant'),
        ),
    ]
