# Generated by Django 5.1.2 on 2026-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_customer_unique_customer_name_per_tenant_and_more'),
        ('technician_portal', '0046_replacement_deleted_at'),
        ('tenants', '0020_copy_platform_branding_to_owner_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_email_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_fleet_name_per_tenant',
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When set, this customer is soft-deleted and excluded from normal querysets', null=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_type', 'FLEET'), ('deleted_at__isnull', True)), fields=('tenant', 'name'), name='unique_fleet_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('email__isnull', False)), fields=('tenant', 'email'), name='unique_customer_email_per_tenant'),
        ),
    ]
