# Generated by Django 5.1.2 on 2026-08-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_customer_unique_customer_email_per_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="review_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="Customer opted out of review request emails/texts",
            ),
        ),
    ]
