# Generated by Django 5.1.2 on 2026-08-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_customer_unique_customer_email_per_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sms_opt_in',
            field=models.BooleanField(default=False, help_text='Customer agreed to receive service texts (invoice links, review requests)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_opt_in_at',
            field=models.DateTimeField(blank=True, help_text='When SMS consent was recorded', null=True),
        ),
    ]
