# Generated by Django 5.1.2 on 2026-08-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customer_sms_opt_in_customer_sms_opt_in_at'),
        ('core', '0025_update_request_received_wording'),
    ]

    operations = [
    ]
