# Generated by Django 5.1.2 on 2026-09-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_needs_assignment_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotificationpreference',
            name='sms_consent_at',
            field=models.DateTimeField(blank=True, help_text='When this person themselves agreed to receive texts', null=True),
        ),
        migrations.AddField(
            model_name='customernotificationpreference',
            name='sms_consent_source',
            field=models.CharField(blank=True, choices=[('SELF_SERVICE', 'Turned on by the recipient in their own settings'), ('IMPORTED', 'Recorded outside the app (documented separately)')], help_text='How that consent was captured', max_length=20),
        ),
        migrations.AddField(
            model_name='techniciannotificationpreference',
            name='sms_consent_at',
            field=models.DateTimeField(blank=True, help_text='When this person themselves agreed to receive texts', null=True),
        ),
        migrations.AddField(
            model_name='techniciannotificationpreference',
            name='sms_consent_source',
            field=models.CharField(blank=True, choices=[('SELF_SERVICE', 'Turned on by the recipient in their own settings'), ('IMPORTED', 'Recorded outside the app (documented separately)')], help_text='How that consent was captured', max_length=20),
        ),
    ]
