# Generated by Django 5.1.2 on 2026-03-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='portal',
            field=models.CharField(choices=[('customer', 'Customer Portal'), ('technician', 'Technician Portal'), ('admin', 'Admin Portal'), ('unified', 'Unified Login')], default='unified', max_length=20),
        ),
    ]
