# Generated by Django 5.1.2 on 2026-09-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_add_unified_portal_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditlog',
            name='event_type',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('password_changed', 'Password Changed'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('suspicious_activity', 'Suspicious Activity Detected'), ('data_export', 'Data Exported'), ('settings_changed', 'Settings Changed'), ('claim_created', 'Insurance Claim Created'), ('claim_updated', 'Insurance Claim Updated'), ('claim_payment', 'Insurance Claim Payment Recorded'), ('claim_closed', 'Insurance Claim Closed'), ('claim_reopened', 'Insurance Claim Reopened')], max_length=50),
        ),
    ]
