# Generated by Django 5.1.2 on 2026-01-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_tenant_fk'),
        ('core', '0013_add_primary_technician'),
        ('tenants', '0006_add_assignment_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'invoice_number'), name='unique_invoice_number_per_tenant'),
        ),
    ]
