# Generated by Django 5.1.2 on 2026-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingconfig_invoice_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingconfig',
            name='default_due_days',
            field=models.PositiveIntegerField(default=0, help_text='Default days until invoice is due (0 = due on receipt/COD). Overridden by payment terms if set (e.g., NET30 = 30 days).'),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='invoice_number_prefix',
            field=models.CharField(default='INV', help_text='Prefix for auto-generated invoice numbers (e.g., INV → INV-1-20260131...)', max_length=20),
        ),
    ]
