# Generated by Django 5.1.2 on 2026-02-01 17:31

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingconfig_invoice_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Fallback tax rate if city lookup fails (percentage). 0 = no fallback.', max_digits=5),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='tax_enabled',
            field=models.BooleanField(default=False, help_text='Enable sales tax calculation on invoices. When disabled, all invoices have zero tax.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated tax amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Tax rate applied (percentage, e.g., 9.500 = 9.5%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='default_due_days',
            field=models.PositiveIntegerField(default=0, help_text='Default days until invoice is due (0 = due on receipt/COD). Overridden by payment terms if set (e.g., NET30 = 30 days).'),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='invoice_number_prefix',
            field=models.CharField(default='INV', help_text='Prefix for auto-generated invoice numbers (e.g., INV → INV-1-20260131...)', max_length=20),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('county', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, default='AR', max_length=2)),
                ('zip_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('state_rate', models.DecimalField(decimal_places=3, default=Decimal('6.500'), max_digits=5)),
                ('county_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5)),
                ('city_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5)),
                ('special_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5)),
                ('total_rate', models.DecimalField(db_index=True, decimal_places=3, help_text='Combined total rate (state + county + city + special)', max_digits=5)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['state', 'city'],
                'indexes': [models.Index(fields=['city', 'state'], name='billing_tax_city_e253cb_idx'), models.Index(fields=['zip_code'], name='billing_tax_zip_cod_334788_idx')],
            },
        ),
    ]
