# Generated by Django 5.1.2 on 2026-02-01 17:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_sales_tax_system'),
        ('tenants', '0006_add_assignment_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='total_rate',
            field=models.DecimalField(db_index=True, decimal_places=3, default=Decimal('0.000'), help_text='Auto-calculated: state + county + city + special', max_digits=5),
        ),
    ]
