# Generated by Django 5.1.2 on 2026-02-01 21:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_tax_rate_tenant_and_auto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='city_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='City portion of tax rate', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='county_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='County portion of tax rate', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='special_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Special district portion of tax rate', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='State portion of tax rate', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Combined tax rate applied (percentage, e.g., 9.500 = 9.5%)', max_digits=5),
        ),
    ]
