# Generated by Django 5.1.2 on 2026-02-01 22:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_tax_rate_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='city_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='City sales tax rate (percentage)', max_digits=5),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='county_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='County sales tax rate (percentage)', max_digits=5),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='special_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Special district tax rate (percentage)', max_digits=5),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='state_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('6.500'), help_text='State sales tax rate (percentage)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Combined tax rate (auto-calculated from components). Percentage, e.g. 9.500 = 9.5%.', max_digits=5),
        ),
    ]
