# Generated by Django 5.1.2 on 2026-02-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_billingconfig_tax_rate_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='batch_invoice_auto_send',
            field=models.BooleanField(default=False, help_text='Automatically send batch invoices via email (otherwise creates as DRAFT)'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='batch_invoice_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day to run batch invoicing. For weekly: 0=Mon, 6=Sun. For monthly: 1-28.'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='batch_invoice_frequency',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='disabled', help_text='How often to auto-generate batch invoices for fleet customers', max_length=20),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='overdue_reminder_days',
            field=models.CharField(default='7,14,30', help_text='Days after due date to send reminders (comma-separated, e.g., "7,14,30")', max_length=50),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='overdue_reminder_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic reminder emails for overdue invoices'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='overdue_reminder_subject',
            field=models.CharField(default='Reminder: Invoice #{invoice_number} is overdue', help_text='Email subject template. Use {invoice_number}, {customer_name}, {amount_due}, {days_overdue}', max_length=200),
        ),
    ]
