# Generated by Django 5.1.2 on 2026-02-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_billingconfig_default_due_days_and_more'),
        ('billing', '0009_billingconfig_tax_rate_breakdown'),
    ]

    operations = [
    ]
