# Generated by Django 5.1.2 on 2026-02-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_add_automation_config'),
        ('billing', '0010_merge_20260201_2226'),
    ]

    operations = [
    ]
