# Generated by Django 5.1.2 on 2026-03-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_merge_20260214_1611'),
        ('core', '0018_seed_repair_notification_templates'),
        ('tenants', '0010_add_grace_period_and_alerts_sent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='billing_invoice_created_at_idx'),
        ),
    ]
