# Generated by Amelia — adds tenant FK to BillingConfig (multi-tenant billing)

from django.db import migrations, models
import django.db.models.deletion


def assign_billing_config_to_tenants(apps, schema_editor):
    """
    Data migration: assign existing BillingConfig rows to tenants.

    Strategy:
    - If there's exactly one BillingConfig and at least one Tenant,
      assign the config to the first tenant (by pk).
    - If there are multiple tenants, create copies for each additional tenant.
    - If there are no tenants (fresh install), do nothing — get_for_tenant()
      will create configs on demand.
    """
    BillingConfig = apps.get_model('billing', 'BillingConfig')
    Tenant = apps.get_model('tenants', 'Tenant')

    tenants = list(Tenant.objects.order_by('id'))
    if not tenants:
        return

    configs = list(BillingConfig.objects.all())
    if not configs:
        return

    # Assign first config to first tenant
    first_config = configs[0]
    first_config.tenant = tenants[0]
    first_config.save()

    # For any remaining tenants, create copies from the first config
    for tenant in tenants[1:]:
        # Check if this tenant already has a config (shouldn't happen but be safe)
        if BillingConfig.objects.filter(tenant=tenant).exists():
            continue
        BillingConfig.objects.create(
            tenant=tenant,
            company_name=first_config.company_name,
            company_address=first_config.company_address,
            company_city=first_config.company_city,
            company_state=first_config.company_state,
            company_zip=first_config.company_zip,
            company_phone=first_config.company_phone,
            company_email=first_config.company_email,
            company_website=first_config.company_website,
            default_payment_terms=first_config.default_payment_terms,
            default_due_days=first_config.default_due_days,
            invoice_footer_note=first_config.invoice_footer_note,
            invoice_number_prefix=first_config.invoice_number_prefix,
            tax_enabled=first_config.tax_enabled,
            default_tax_rate=first_config.default_tax_rate,
            state_tax_rate=first_config.state_tax_rate,
            county_tax_rate=first_config.county_tax_rate,
            city_tax_rate=first_config.city_tax_rate,
            special_tax_rate=first_config.special_tax_rate,
            overdue_reminder_enabled=first_config.overdue_reminder_enabled,
            overdue_reminder_days=first_config.overdue_reminder_days,
            overdue_reminder_subject=first_config.overdue_reminder_subject,
            batch_invoice_frequency=first_config.batch_invoice_frequency,
            batch_invoice_day=first_config.batch_invoice_day,
            batch_invoice_auto_send=first_config.batch_invoice_auto_send,
        )

    # Remove orphan configs (null tenant, if there were multiple)
    if len(configs) > 1:
        for cfg in configs[1:]:
            if cfg.tenant_id is None:
                cfg.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_add_invoice_created_at_index'),
        ('tenants', '0010_add_grace_period_and_alerts_sent'),
    ]

    operations = [
        # 1. Add nullable tenant FK
        migrations.AddField(
            model_name='billingconfig',
            name='tenant',
            field=models.OneToOneField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='billing_config',
                to='tenants.tenant',
            ),
        ),

        # 2. Drop the singleton_id unique constraint BEFORE data migration
        #    so we can create copies for multiple tenants
        migrations.AlterField(
            model_name='billingconfig',
            name='singleton_id',
            field=models.BooleanField(default=True, editable=False),  # Remove unique=True
        ),

        # 3. Data migration: assign to tenant(s)
        migrations.RunPython(
            assign_billing_config_to_tenants,
            reverse_code=migrations.RunPython.noop,
        ),

        # 4. Make tenant non-nullable (OneToOne handles unique constraint)
        migrations.AlterField(
            model_name='billingconfig',
            name='tenant',
            field=models.OneToOneField(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='billing_config',
                to='tenants.tenant',
            ),
        ),

        # 5. Remove singleton_id field
        migrations.RemoveField(
            model_name='billingconfig',
            name='singleton_id',
        ),
    ]
