# Generated by Django 5.1.2 on 2026-03-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_billingconfig_tenant_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingconfig',
            options={'verbose_name': 'Billing Configuration', 'verbose_name_plural': 'Billing Configurations'},
        ),
    ]
