# Generated by Django 5.1.2 on 2026-03-14 11:08

from django.db import migrations, models


def fix_hardcoded_company_names(apps, schema_editor):
    """
    Fix existing BillingConfig rows that still have the hardcoded placeholder
    'Rockstar Windshield Repair' (or an empty string after the field change).
    Replace with the actual tenant name so invoices are correctly branded.
    """
    BillingConfig = apps.get_model('billing', 'BillingConfig')
    for config in BillingConfig.objects.select_related('tenant').all():
        if config.company_name in ('Rockstar Windshield Repair', '', None):
            if config.tenant:
                config.company_name = config.tenant.name
                config.save(update_fields=['company_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_billingconfig_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingconfig',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Company name displayed on invoices (defaults to shop name if blank)', max_length=200),
        ),
        migrations.RunPython(fix_hardcoded_company_names, migrations.RunPython.noop),
    ]
