# Generated by Django 5.1.2 on 2026-03-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_billing_config_company_name_default'),
        ('technician_portal', '0033_backfill_viscosity_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='replacement',
            field=models.ForeignKey(blank=True, help_text='The replacement this line item is for. PROTECT prevents deleting invoiced replacements.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_items', to='technician_portal.replacement'),
        ),
    ]
