# Generated by Django 5.1.2 on 2026-03-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_add_replacement_fk_to_invoice_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When set, this invoice is soft-deleted and excluded from normal querysets', null=True),
        ),
    ]
