# Generated by Django 5.1.2 on 2026-05-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_add_replacement_fk_to_invoice_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, help_text='Customer-facing description or summary for this invoice'),
        ),
    ]
