# Generated by Django 5.1.2 on 2026-03-17 21:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_invoice_deleted_at'),
        ('tenants', '0012_tenant_stripe_connected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default platform fee % on invoice payments (e.g. 2.50 = 2.5%)', max_digits=5)),
                ('competition_pool_enabled', models.BooleanField(default=False, help_text='Whether the competition pool feature is active')),
                ('competition_pool_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% of subscription payments routed to competition pool', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configuration',
            },
        ),
        migrations.CreateModel(
            name='PlatformFeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(db_index=True, help_text='Stripe PaymentIntent ID (pi_...)', max_length=255)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total payment amount in dollars', max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Platform fee collected in dollars', max_digits=10)),
                ('fee_percent', models.DecimalField(decimal_places=2, help_text='Fee rate at time of charge (percentage)', max_digits=5)),
                ('stripe_account_id', models.CharField(help_text="Shop's connected account ID (acct_...)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fee_records', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fee_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Platform Fee Record',
                'verbose_name_plural': 'Platform Fee Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='billing_pla_tenant__0a97f2_idx')],
            },
        ),
    ]
