# Generated by Django 5.1.2 on 2026-03-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_platformconfig_platformfeerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='invoice_email_template',
            field=models.TextField(blank=True, default='', help_text='Default email body when sending an invoice. Use {customer_name}, {invoice_number}, {total}, {due_date}, {company_name} as placeholders. Leave blank to use the system default.'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='reminder_email_template',
            field=models.TextField(blank=True, default='', help_text='Default email body for payment reminders. Use {customer_name}, {invoice_number}, {total}, {amount_due}, {due_date}, {days_overdue}, {company_name} as placeholders. Leave blank to use the system default.'),
        ),
    ]
