# Generated by Django 5.1.2 on 2026-03-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_add_email_templates_to_billing_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingconfig',
            name='invoice_email_template',
            field=models.TextField(blank=True, default='', help_text='Default email body when sending an invoice. Use {customer_name}, {invoice_number}, {total}, {invoice_date}, {company_name} as placeholders. Leave blank to use the system default.'),
        ),
    ]
