# Generated by Django 5.1.2 on 2026-05-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_code119_invoice_email_template_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, help_text='Customer-facing description or summary for this invoice'),
        ),
    ]
