# Generated by Django 5.1.2 on 2026-07-10 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_invoice_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_payment_id', ''), _negated=True), fields=('stripe_payment_id',), name='unique_stripe_payment_id_when_set'),
        ),
    ]
