# Generated by Django 5.1.2 on 2026-07-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_payment_stripe_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_days_overdue',
            field=models.IntegerField(blank=True, help_text='Highest overdue-reminder tier (in days) already sent for this invoice', null=True),
        ),
    ]
