# Generated by Django 5.1.2 on 2026-07-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_datefield_localdate_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_sent_to',
            field=models.EmailField(blank=True, default='', help_text='Recipient email of the most recent invoice send', max_length=254),
        ),
    ]
