# Generated by Django 5.1.2 on 2026-07-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_invoice_last_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='first_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the most recent invoice email went out (sent_at keeps the first send)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
