# Generated by Django 5.1.2 on 2026-07-27 17:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_invoice_last_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='tax_configured',
            field=models.BooleanField(default=False, help_text='Owner has explicitly answered "Do you charge sales tax?" Until then the shop sees the tax setup banner.'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='taxable',
            field=models.BooleanField(default=True, help_text='Include this line in the tax calculation'),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='state_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='State sales tax rate (percentage)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='state',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='state_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5),
        ),
    ]
