# Generated by Django 5.1.2 on 2026-07-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_invoice_first_viewed_at_invoice_last_sent_at_and_more'),
        ('billing', '0027_backfill_tax_enabled'),
    ]

    operations = [
    ]
