# Generated by Django 5.1.2 on 2026-07-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_merge_20260727_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email_delivery_detail',
            field=models.CharField(blank=True, default='', help_text='Short diagnostic from the mail server (e.g. bounce reason)', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_delivery_status',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('bounced', 'Bounced'), ('complained', 'Marked as spam'), ('rejected', 'Rejected')], default='', help_text='Delivery status of the most recent invoice email (from SES events)', max_length=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_delivery_status_at',
            field=models.DateTimeField(blank=True, help_text='When the delivery status last changed', null=True),
        ),
    ]
