# Generated by Django 5.1.2 on 2026-08-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_invoice_email_delivery_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='next_invoice_number',
            field=models.PositiveIntegerField(default=1001, help_text='The number your next invoice will get. Counts up from here: INV-1001, INV-1002, … Set it to continue from your old books.'),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='invoice_number_prefix',
            field=models.CharField(default='INV', help_text='Prefix for invoice numbers (e.g., INV → INV-1001)', max_length=20),
        ),
    ]
