# Generated by Django 5.1.2 on 2026-08-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_billingconfig_next_invoice_number_and_more'),
        ('tenants', '0022_onboardingstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCheckoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('stripe_account_id', models.CharField(help_text='Connect account the session was created on (acct_...)', max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETE', 'Complete'), ('EXPIRED', 'Expired')], default='OPEN', help_text='Last status seen from Stripe; OPEN until confirmed otherwise', max_length=10)),
                ('payment_intent_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_attempts', to='billing.invoice')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_attempts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'status'], name='billing_str_invoice_333897_idx'), models.Index(fields=['status', 'created_at'], name='billing_str_status_f17af1_idx')],
            },
        ),
    ]
