# Generated by Django 5.1.2 on 2026-08-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_stripecheckoutattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='sms_invoicing_enabled',
            field=models.BooleanField(default=False, help_text='Offer "Text the invoice" when sending to customers with a mobile number on file'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_sms_at',
            field=models.DateTimeField(blank=True, help_text='When the most recent invoice text went out', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_sms_to',
            field=models.CharField(blank=True, default='', help_text='Phone number the invoice link was last texted to', max_length=20),
        ),
    ]
