# Generated by Django 5.1.2 on 2026-08-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_billingconfig_sms_invoicing_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Stripe event id (evt_...). The idempotency key.', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('endpoint', models.CharField(choices=[('subscription', 'Subscription (/api/tenants/webhooks/stripe/)'), ('billing', 'Billing/Connect (/api/billing/stripe/webhook/)')], db_index=True, help_text='Which of our two endpoints received it', max_length=20)),
                ('api_version', models.CharField(blank=True, default='', help_text='API version Stripe shaped this payload with. Differs from settings.STRIPE_API_VERSION when the Dashboard endpoint is pinned to something else.', max_length=50)),
                ('account_id', models.CharField(blank=True, default='', help_text='Connected account id for Connect events (acct_...)', max_length=50)),
                ('livemode', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored (nothing to do)'), ('failed', 'Failed (Stripe will retry)')], db_index=True, default='processing', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='How many times we have tried to process it')),
                ('created_ts', models.BigIntegerField(blank=True, help_text="Stripe's event.created (unix). Used to reject out-of-order state writes.", null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='The full event body, for replay and forensics.')),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
                'ordering': ['-first_seen_at'],
                'indexes': [models.Index(fields=['status', 'first_seen_at'], name='billing_str_status_6205c2_idx'), models.Index(fields=['event_type', 'first_seen_at'], name='billing_str_event_t_5d3a48_idx')],
            },
        ),
    ]
