# Generated by Django 5.1.2 on 2026-08-11 04:14

from django.db import migrations, models


def dedupe_fee_records(apps, schema_editor):
    """Drop duplicate fee rows before the unique constraint is applied.

    Two paths can record the same PaymentIntent -- the webhook and the
    15-minute reconcile sweep -- and until now nothing but an
    `.exists()` check stood between them, which does not hold under a
    race. If prod happens to contain a duplicate, AddConstraint below
    would abort the whole deploy. Keep the oldest row per PaymentIntent.
    """
    PlatformFeeRecord = apps.get_model('billing', 'PlatformFeeRecord')
    seen = set()
    doomed = []
    qs = PlatformFeeRecord.objects.order_by('payment_intent_id', 'id')
    for pk, pi_id in qs.values_list('id', 'payment_intent_id'):
        if pi_id in seen:
            doomed.append(pk)
        else:
            seen.add(pi_id)
    if doomed:
        PlatformFeeRecord.objects.filter(id__in=doomed).delete()


def noop(apps, schema_editor):
    """Deleted duplicates cannot be resurrected; nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_stripewebhookevent'),
        ('tenants', '0025_tenant_platform_fee_fixed_cents_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_fee_records, noop),
        migrations.AddField(
            model_name='platformconfig',
            name='default_fee_fixed_cents',
            field=models.PositiveIntegerField(default=0, help_text='Default fixed component per transaction, in cents (e.g. 25 = $0.25). On a $50 chip repair a percentage alone is noise; percent + fixed is the industry-standard shape.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='fee_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for platform fees on invoice payments. While off, no application_fee_amount is charged regardless of the rates below.'),
        ),
        migrations.AddField(
            model_name='platformfeerecord',
            name='fee_fixed_cents',
            field=models.PositiveIntegerField(default=0, help_text='Fixed component of the fee at time of charge, in cents'),
        ),
        migrations.AlterField(
            model_name='platformfeerecord',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, help_text='Effective fee rate at time of charge, derived from the raw amounts. With a fixed component this is the blended rate, which is still a true statement about what was taken.', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='platformfeerecord',
            index=models.Index(fields=['created_at'], name='billing_pla_created_9f320e_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformfeerecord',
            constraint=models.UniqueConstraint(fields=('payment_intent_id',), name='uniq_platform_fee_payment_intent'),
        ),
    ]
