# Generated by Django 5.1.2 on 2026-09-08 19:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import rs_systems.model_mixins
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_strip_vehicle_from_line_descriptions'),
        ('core', '0034_needs_assignment_template'),
        ('tenants', '0027_alter_tenant_subscription_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='next_quote_number',
            field=models.PositiveIntegerField(default=1001, help_text='The number your next quote will get. Counts up from here.'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='quote_number_prefix',
            field=models.CharField(default='Q', help_text='Prefix for quote numbers (e.g., Q → Q-1001)', max_length=20),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='quote_valid_days',
            field=models.PositiveIntegerField(default=30, help_text='How many days a new quote stays open for the customer to accept.'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('SUPERSEDED', 'Revised')], db_index=True, default='DRAFT', max_length=20)),
                ('quote_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(help_text='Last day the customer can accept at these prices.')),
                ('unit_number', models.CharField(blank=True, max_length=50)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=50)),
                ('vehicle_model', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('no_tax', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Shown to the customer.')),
                ('internal_notes', models.TextField(blank=True, help_text='Shop only.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_email', models.EmailField(blank=True, max_length=254)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_via', models.CharField(blank=True, choices=[('link', 'Emailed link'), ('portal', 'Customer portal'), ('shop', 'Recorded by the shop')], max_length=20)),
                ('responded_by_name', models.CharField(blank=True, max_length=100)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='core.customer')),
                ('supersedes', models.ForeignKey(blank=True, help_text='The quote this one replaced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='billing.quote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-quote_date', '-id'],
            },
            bases=(rs_systems.model_mixins.AutoUpdateTimestampMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('REPAIR', 'Repair'), ('REPLACEMENT', 'Replacement'), ('OTHER', 'Other charge')], default='REPAIR', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('unit_number', models.CharField(blank=True, max_length=50)),
                ('damage_type', models.CharField(blank=True, max_length=100)),
                ('glass_position', models.CharField(blank=True, max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.quote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['tenant', 'status'], name='quote_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer', 'status'], name='quote_customer_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('tenant', 'quote_number'), name='unique_quote_number_per_tenant'),
        ),
    ]
