# Generated by Django 5.1.2 on 2026-09-16 19:19

import django.db.models.deletion
import django.utils.timezone
import rs_systems.model_mixins
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_quotes'),
        ('tenants', '0027_alter_tenant_subscription_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(blank=True, help_text='Insurance company', max_length=100)),
                ('claim_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('authorization_number', models.CharField(blank=True, max_length=50)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, help_text="The customer's share. Paid to the shop by the customer, never by the insurer.", max_digits=10, null=True)),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Blank means the invoice total minus the deductible.', max_digits=10, null=True)),
                ('authorized_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('AUTHORIZED', 'Authorized'), ('SHORT', 'Short-paid'), ('PAID', 'Paid in full'), ('CLOSED', 'Closed')], db_index=True, default='SUBMITTED', max_length=20)),
                ('submitted_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, help_text='Shop only — who you spoke to, what they said.')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('written_off_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-submitted_on', '-id'],
            },
            bases=(rs_systems.model_mixins.AutoUpdateTimestampMixin, models.Model),
        ),
        migrations.AddField(
            model_name='payment',
            name='claim',
            field=models.ForeignKey(blank=True, help_text='The insurance claim this payment settles, if it came from the insurer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.insuranceclaim'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['tenant', 'status'], name='claim_tenant_status_idx'),
        ),
    ]
