"""
Django settings for rs_systems project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
# .env file is in the project root directory
load_dotenv(os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================
# CORE CONFIGURATION
# =========================================

# Environment detection
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')
print(f"Current environment: {ENVIRONMENT}")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY and ENVIRONMENT != 'production':
    SECRET_KEY = 'django-insecure-dev-only-key-not-for-production'
elif not SECRET_KEY:
    raise ValueError("No SECRET_KEY set in environment variables")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True' if ENVIRONMENT != 'production' else 'False').lower() == 'true'

# =========================================
# DEPLOYMENT & HOSTING CONFIGURATION
# =========================================

# Configure allowed hosts
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000').split(',')

# Cross-Origin Resource Sharing (CORS) settings
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:8000').split(',')
CORS_ALLOW_CREDENTIALS = os.environ.get('CORS_ALLOW_CREDENTIALS', 'True').lower() == 'true'

# =========================================
# STATIC FILES CONFIGURATION
# =========================================

STATIC_URL = os.environ.get('STATIC_URL', '/static/')
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Ensure whitenoise is installed for static file serving in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# =========================================
# FILE UPLOAD CONFIGURATION
# =========================================

# File upload size limits - Allow up to 10MB for image uploads
# This provides headroom beyond the 5MB validation in the application
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# =========================================
# MEDIA FILES & AWS S3 CONFIGURATION
# =========================================

# AWS S3 settings for media files
USE_S3 = os.environ.get('USE_S3', 'False').lower() == 'true'

if USE_S3:
    # AWS S3 settings
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_VERIFY = True
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # Media files URL configuration for S3
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/'
else:
    # Local media files settings (development)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

    # Ensure media directories exist
    os.makedirs(os.path.join(MEDIA_ROOT, 'repair_photos', 'before'), exist_ok=True)
    os.makedirs(os.path.join(MEDIA_ROOT, 'repair_photos', 'after'), exist_ok=True)

# =========================================
# SECURITY CONFIGURATION
# =========================================

# Determine if we should use HTTPS
USE_HTTPS = os.environ.get('USE_HTTPS', 'False').lower() == 'true'
IS_CLOUD_DEPLOYMENT = any(host.endswith(('.railway.app', '.herokuapp.com', '.vercel.app')) for host in ALLOWED_HOSTS)

# On cloud deployments, we need specific security settings
if IS_CLOUD_DEPLOYMENT:
    print("Cloud deployment detected")
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # Cloud providers handle SSL termination
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
elif ENVIRONMENT == 'production' and USE_HTTPS:
    print("Production with HTTPS enabled")
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    print("HTTPS disabled")
    SECURE_PROXY_SSL_HEADER = None
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# =========================================
# DATABASE CONFIGURATION
# =========================================

# Get database URL based on selection in .env
USE_AWS_DB = os.environ.get('USE_AWS_DB', 'False').lower() == 'true'

if USE_AWS_DB:
    print("Using AWS database")
    db_url = os.environ.get('AWS_DATABASE_URL')
else:
    print("Using LOCAL database")
    db_url = os.environ.get('LOCAL_DATABASE_URL')

if not db_url:
    if ENVIRONMENT == 'production':
        # CRITICAL: Never use SQLite in production - it's ephemeral on AWS!
        raise ValueError("CRITICAL: No DATABASE_URL configured! Production requires a persistent database (RDS PostgreSQL).")
    
    print("WARNING: No database URL configured! Using SQLite for development only")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Use the configured database
    masked_url = db_url.split('@')[-1] if '@' in db_url else db_url
    print(f"Database URL: {masked_url}")
    
    DATABASES = {
        'default': dj_database_url.config(default=db_url, conn_max_age=600),
    }
    # Ensure TEST config exists for Django test runner
    DATABASES['default'].setdefault('TEST', {})
    
    # For production, ensure we're using a persistent database
    if ENVIRONMENT == 'production' and 'sqlite' in db_url.lower():
        raise ValueError("CRITICAL: SQLite is not allowed in production! Use RDS PostgreSQL for data persistence.")

# =========================================
# APPLICATION DEFINITION
# =========================================

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.technician_portal',
    'apps.customer_portal',
    'apps.rewards_referrals',
    'apps.security',
    'apps.clawdbot',
    'apps.billing',
    'apps.tenants',
    'apps.saas',
    'core',  # Core app (includes Customer model and notification system)
    'drf_spectacular',
    'django_cleanup.apps.CleanupConfig',  # Must be last - automatically deletes files when models are deleted
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Whitenoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.tenants.middleware.TenantMiddleware',  # Multi-tenant resolution
    'common.portal_middleware.PortalAccessMiddleware',  # Portal access control
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rs_systems.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'rs_systems' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rs_systems.wsgi.application'

# =========================================
# AUTHENTICATION CONFIGURATION
# =========================================

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'

# =========================================
# REST FRAMEWORK CONFIGURATION
# =========================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Token-based auth
        'rest_framework.authentication.SessionAuthentication',  # Session-based auth
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '60/minute',
        'signup': '5/hour',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'RSWR Systems API',
    'DESCRIPTION': 'API documentation for RSWR Systems',
    'VERSION': '1.0.0',
}

# =========================================
# INTERNATIONALIZATION CONFIGURATION
# =========================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = os.environ.get('TIME_ZONE', 'America/Chicago')
USE_I18N = True
USE_TZ = True

# =========================================
# DEFAULT FIELDS CONFIGURATION
# =========================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================================
# EMAIL CONFIGURATION
# =========================================

# Development: Email backend (prints to console for testing)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Console backend (for development)

# SendGrid SMTP Backend (enabled for notification system)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY')

# Email sender information
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'notifications@rockstarwindshield.repair')
DEFAULT_FROM_NAME = os.environ.get('DEFAULT_FROM_NAME', 'RS Systems')
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # For error emails

# =========================================
# SMS CONFIGURATION (AWS SNS)
# =========================================

# AWS SNS Configuration (for test_sns command)
# In development, these are only used if you configure AWS SNS
AWS_SNS_REGION_NAME = os.environ.get('AWS_SNS_REGION', 'us-east-1')
SMS_ENABLED = os.environ.get('SMS_ENABLED', 'False').lower() == 'true'

# =========================================
# STRIPE CONFIGURATION
# =========================================

STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# Stripe mode detection (auto-detect from key prefix)
STRIPE_TEST_MODE = STRIPE_SECRET_KEY.startswith('sk_test_') if STRIPE_SECRET_KEY else True

# Invoice defaults
INVOICE_DEFAULT_DUE_DAYS = 30
INVOICE_FROM_EMAIL = os.environ.get('INVOICE_FROM_EMAIL', 'billing@rockstarwindshield.repair')

# =========================================
# CELERY CONFIGURATION
# =========================================

# Celery broker and result backend (Redis)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Celery serialization settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Timezone configuration (match Django timezone)
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Task routing (send notification tasks to specific queue)
CELERY_TASK_ROUTES = {
    'core.tasks.send_notification_email': {'queue': 'notifications'},
    'core.tasks.send_notification_sms': {'queue': 'notifications'},
    'core.tasks.retry_failed_notifications': {'queue': 'notifications'},
    'core.tasks.send_daily_digests': {'queue': 'notifications'},
    'core.tasks.cleanup_old_delivery_logs': {'queue': 'maintenance'},
}

# Task time limits (prevent hanging tasks)
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes soft limit (raises SoftTimeLimitExceeded)

# Retry configuration
CELERY_TASK_ACKS_LATE = True  # Tasks acknowledged after completion (safer for critical tasks)
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Requeue if worker crashes

# Worker concurrency (number of worker processes)
CELERY_WORKER_CONCURRENCY = int(os.environ.get('CELERY_CONCURRENCY', 4))

# Development: Uncomment to run tasks synchronously for easier debugging
# CELERY_TASK_ALWAYS_EAGER = True
# CELERY_TASK_EAGER_PROPAGATES = True

# =========================================
# CACHING CONFIGURATION
# =========================================
# Use Redis in production, fall back to local memory cache for dev without Redis

REDIS_CACHE_URL = os.environ.get('REDIS_CACHE_URL', 'redis://localhost:6379/1')

def _redis_available():
    """Check if Redis is reachable (called once at startup)."""
    try:
        import socket
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(1)
        s.connect(('localhost', 6379))
        s.close()
        return True
    except (socket.error, OSError):
        return False

if _redis_available():
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_CACHE_URL,
            'KEY_PREFIX': 'rs_systems',
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'KEY_PREFIX': 'rs_systems',
            'TIMEOUT': 300,
        }
    }

# =========================================
# LOGGING CONFIGURATION
# =========================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
