# Generated by Django 5.1.2 on 2026-03-07 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_referrals', '0004_rewardtype_rewardredemption_applied_to_repair_and_more'),
        ('tenants', '0009_add_pricing_tiers_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardoption',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_options', to='tenants.tenant'),
        ),
    ]
