# Generated by Django 5.1.2 on 2026-03-07 22:12

from django.db import migrations


def backfill_reward_option_tenant(apps, schema_editor):
    """Assign existing RewardOption records to the default tenant."""
    Tenant = apps.get_model('tenants', 'Tenant')
    RewardOption = apps.get_model('rewards_referrals', 'RewardOption')

    default_tenant = Tenant.objects.first()
    if default_tenant:
        RewardOption.objects.filter(tenant__isnull=True).update(tenant=default_tenant)


def reverse_backfill(apps, schema_editor):
    """Remove tenant assignment (set to null)."""
    RewardOption = apps.get_model('rewards_referrals', 'RewardOption')
    RewardOption.objects.all().update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_referrals', '0005_add_tenant_to_reward_option'),
        ('tenants', '0009_add_pricing_tiers_to_tenant'),
    ]

    operations = [
        migrations.RunPython(backfill_reward_option_tenant, reverse_backfill),
    ]
