# Generated by Django 5.1.2 on 2026-03-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_referrals', '0006_backfill_reward_option_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardredemption',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Special requests from customer'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='preferred_date',
            field=models.DateField(blank=True, help_text="Customer's preferred delivery/fulfillment date", null=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='preferred_time',
            field=models.TimeField(blank=True, help_text="Customer's preferred time", null=True),
        ),
    ]
