# Generated by Django 5.1.2 on 2026-03-24 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_code119_invoice_email_template_helptext'),
        ('customer_portal', '0011_customerinvitation_is_primary_contact'),
        ('rewards_referrals', '0007_rewardredemption_customer_notes_and_more'),
        ('technician_portal', '0035_repair_deleted_at_partial_index'),
        ('tenants', '0016_set_rockstar_platform_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_repair', models.PositiveIntegerField(default=50)),
                ('referral_bonus_referrer', models.PositiveIntegerField(default=500)),
                ('referral_bonus_referred', models.PositiveIntegerField(default=100)),
                ('milestone_5_bonus', models.PositiveIntegerField(default=250)),
                ('milestone_10_bonus', models.PositiveIntegerField(default=500)),
                ('milestone_25_bonus', models.PositiveIntegerField(default=1000)),
                ('points_for_review', models.PositiveIntegerField(default=100)),
                ('points_for_early_payment', models.PositiveIntegerField(default=25)),
                ('points_expiry_days', models.PositiveIntegerField(default=365, help_text='0 = never expire')),
                ('expiry_warning_days', models.PositiveIntegerField(default=30)),
                ('program_name', models.CharField(default='Rewards', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Loyalty Configuration',
                'verbose_name_plural': 'Loyalty Configurations',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for earn, negative for spend')),
                ('balance_after', models.IntegerField(help_text='Running balance after this transaction')),
                ('transaction_type', models.CharField(choices=[('repair_complete', 'Repair Complete'), ('referral_made', 'Referral Made'), ('referral_received', 'Referral Received'), ('milestone_bonus', 'Milestone Bonus'), ('early_pay_bonus', 'Early Pay Bonus'), ('review_bonus', 'Review Bonus'), ('tier_bonus', 'Tier Bonus'), ('manual_adjustment', 'Manual Adjustment'), ('redemption', 'Redemption'), ('expiration', 'Expiration')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_point_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='customer_portal.customeruser')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='billing.payment')),
                ('related_redemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='rewards_referrals.rewardredemption')),
                ('related_repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='technician_portal.repair')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_user', '-created_at'], name='rewards_ref_custome_7ea25f_idx'), models.Index(fields=['tenant', 'transaction_type'], name='rewards_ref_tenant__f28ffd_idx'), models.Index(condition=models.Q(('expired', False), ('expires_at__isnull', False)), fields=['expires_at'], name='idx_pt_unexpired')],
            },
        ),
    ]
