# Generated by Django 5.1.2 on 2026-03-24 14:31

from django.db import migrations


def backfill_reward_tenant_and_ledger(apps, schema_editor):
    """
    1. Backfill tenant FK on Reward from customer_user.customer.tenant
    2. Create a PointTransaction for each Reward with points > 0
    3. Create a LoyaltyConfig for each tenant that has Reward records
    """
    Reward = apps.get_model('rewards_referrals', 'Reward')
    PointTransaction = apps.get_model('rewards_referrals', 'PointTransaction')
    LoyaltyConfig = apps.get_model('rewards_referrals', 'LoyaltyConfig')

    seen_tenants = set()

    for reward in Reward.objects.select_related('customer_user__customer__tenant').all():
        tenant = reward.customer_user.customer.tenant
        if tenant is None:
            continue

        # Backfill tenant on Reward
        if reward.tenant_id is None:
            reward.tenant = tenant
            reward.save(update_fields=['tenant'])

        seen_tenants.add(tenant.pk)

        # Create legacy balance PointTransaction
        if reward.points > 0:
            PointTransaction.objects.create(
                tenant=tenant,
                customer_user=reward.customer_user,
                amount=reward.points,
                balance_after=reward.points,
                transaction_type='manual_adjustment',
                description='Legacy balance migration',
            )

    # Create LoyaltyConfig for each tenant with rewards
    for tenant_pk in seen_tenants:
        LoyaltyConfig.objects.get_or_create(tenant_id=tenant_pk)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_referrals', '0008_loyalty_phase1_models'),
    ]

    operations = [
        migrations.RunPython(backfill_reward_tenant_and_ledger, noop),
    ]
