# Generated by Django 5.1.2 on 2026-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0011_customerinvitation_is_primary_contact'),
        ('rewards_referrals', '0009_loyalty_phase1_backfill'),
        ('tenants', '0016_set_rockstar_platform_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.UniqueConstraint(fields=('customer_user',), name='unique_reward_per_customer_user'),
        ),
    ]
