# Generated by Django 5.1.2 on 2026-03-25 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_referrals', '0011_referralcode_unique_customer_user'),
        ('tenants', '0016_set_rockstar_platform_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyconfig',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tenants.tenant'),
        ),
    ]
