# Generated by Django 5.1.2 on 2026-03-25 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0011_customerinvitation_is_primary_contact'),
        ('rewards_referrals', '0012_alter_loyaltyconfig_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='customer_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_portal.customeruser'),
        ),
    ]
