# Generated by Django 5.1.2 on 2026-07-23 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_referrals', '0014_code210_add_scheduled_status'),
        ('technician_portal', '0044_backfill_can_replace'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtransaction',
            name='related_replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='technician_portal.replacement'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='applied_to_replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_rewards', to='technician_portal.replacement'),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('repair_complete', 'Repair Complete'), ('replacement_complete', 'Replacement Complete'), ('referral_made', 'Referral Made'), ('referral_received', 'Referral Received'), ('milestone_bonus', 'Milestone Bonus'), ('early_pay_bonus', 'Early Pay Bonus'), ('review_bonus', 'Review Bonus'), ('tier_bonus', 'Tier Bonus'), ('manual_adjustment', 'Manual Adjustment'), ('redemption', 'Redemption'), ('expiration', 'Expiration')], max_length=30),
        ),
    ]
