# Generated by Django 5.1.2 on 2026-08-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_referrals', '0019_referral_pending_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('repair_complete', 'Repair Complete'), ('replacement_complete', 'Replacement Complete'), ('referral_made', 'Referral Made'), ('referral_received', 'Referral Received'), ('milestone_bonus', 'Milestone Bonus'), ('early_pay_bonus', 'Early Pay Bonus'), ('review_bonus', 'Review Bonus'), ('tier_bonus', 'Tier Bonus'), ('manual_adjustment', 'Manual Adjustment'), ('redemption', 'Redemption'), ('redemption_refund', 'Redemption Refund'), ('expiration', 'Expiration')], max_length=30),
        ),
    ]
