# Generated by Django 5.1.2 on 2026-08-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_referrals', '0020_alter_pointtransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyconfig',
            name='auto_apply_rewards',
            field=models.BooleanField(default=False, help_text='Automatically use the oldest waiting discount reward when a job is completed. When off, the job form asks instead.'),
        ),
    ]
