# Generated by Django 5.1.2 on 2026-01-28 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Business name (e.g., 'Rockstar Windshield Repair')", max_length=200)),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g., 'rockstar-windshield')", unique=True)),
                ('subdomain', models.CharField(help_text="For future subdomain-based routing (e.g., 'rockstar')", max_length=63, unique=True)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='tenants/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer ID for platform billing', max_length=50)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe Subscription ID for platform billing', max_length=50)),
                ('plan', models.CharField(choices=[('trial', 'Free Trial'), ('starter', 'Starter'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('owner', models.ForeignKey(help_text='The primary owner of this business', on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('technician', 'Technician'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership',
                'verbose_name_plural': 'Tenant Memberships',
                'ordering': ['tenant', 'role'],
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
