# Generated by Django 5.1.2 on 2026-01-28 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_create_default_tenant_and_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for monthly billing', max_length=100)),
                ('stripe_annual_price_id', models.CharField(blank=True, help_text='Stripe Price ID for annual billing', max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_repairs_per_month', models.IntegerField(blank=True, help_text='Max repairs per month. null = unlimited.', null=True)),
                ('max_technicians', models.IntegerField(blank=True, help_text='Max active technicians. null = unlimited.', null=True)),
                ('max_customers', models.IntegerField(blank=True, help_text='Max customer accounts. null = unlimited.', null=True)),
                ('max_storage_mb', models.IntegerField(default=500, help_text='Max storage in MB for photos/documents.')),
                ('features', models.JSONField(default=dict, help_text='Feature flags, e.g. {"invoicing": true, "rewards": true, "api_access": false}')),
                ('trial_days', models.IntegerField(default=0, help_text='Number of trial days (0 = not a trial plan)')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'monthly_price'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='trialing', help_text='Current subscription lifecycle status', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='When the free trial began', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Current subscription plan (detailed limits & features)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenants.subscriptionplan'),
        ),
    ]
