# Generated by Django 5.1.2 on 2026-01-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='assignment_strategy',
            field=models.CharField(choices=[('manual', 'Manual — manager assigns all repairs'), ('primary_first', 'Primary Tech First — auto-assign if customer has a primary tech, otherwise queue'), ('auto', 'Smart Auto-Assign — auto-assign based on workload and abilities'), ('round_robin', 'Round Robin — rotate evenly through eligible techs')], default='primary_first', help_text='How new repair requests are assigned to technicians', max_length=20),
        ),
    ]
