# Generated by Django 5.1.2 on 2026-02-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_assignment_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auto_invoice_enabled',
            field=models.BooleanField(default=True, help_text='When enabled, invoices are auto-generated on repair completion (per customer preference). Disable for testing.'),
        ),
    ]
