# Generated by Django 5.1.2 on 2026-02-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_add_auto_invoice_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='use_progressive_pricing',
            field=models.BooleanField(default=True, help_text='When enabled, repair prices decrease with each subsequent repair on a unit. When disabled, every repair uses first-repair pricing.'),
        ),
    ]
