# Generated by Django 5.1.2 on 2026-02-18 03:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_progressive_pricing_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='repair_price_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Price for 1st repair on a unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='repair_price_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Price for 2nd repair on a unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='repair_price_3',
            field=models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Price for 3rd repair on a unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='repair_price_4',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Price for 4th repair on a unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='repair_price_5_plus',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Price for 5th+ repairs on a unit', max_digits=10),
        ),
    ]
