# Generated by Django 5.1.2 on 2026-03-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_add_pricing_tiers_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, help_text='End of the 30-day read-only grace period after subscription expiry', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_alerts_sent',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks which subscription alert emails have been sent, keyed by alert type'),
        ),
    ]
