# Generated by Django 5.1.2 on 2026-03-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_add_grace_period_and_alerts_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee percentage on invoice payments (e.g., 2.00 for 2%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect Account ID (acct_...) for receiving invoice payments', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_connect_charges_enabled',
            field=models.BooleanField(default=False, help_text='Whether the connected account can accept charges'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_connect_onboarding_complete',
            field=models.BooleanField(default=False, help_text='Whether Stripe Connect onboarding (KYC, bank account) is fully complete'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_connect_payouts_enabled',
            field=models.BooleanField(default=False, help_text='Whether the connected account can receive payouts to their bank'),
        ),
    ]
