# Generated by Django 5.1.2 on 2026-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_add_stripe_connect_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stripe_connected_at',
            field=models.DateTimeField(blank=True, help_text='When the Stripe Connect account first became active', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_onboarding_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Onboarding Started'), ('in_review', 'In Review'), ('active', 'Active'), ('restricted', 'Restricted'), ('disabled', 'Disabled')], default='not_started', help_text='Current Stripe Connect onboarding status', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='platform_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override global platform fee for this tenant. Null = use global default.', max_digits=5, null=True),
        ),
    ]
