# Generated by Django 5.1.2 on 2026-03-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_set_live_stripe_price_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='intended_plan',
            field=models.CharField(blank=True, help_text='Plan slug chosen during signup, used to pre-select on upgrade', max_length=20),
        ),
    ]
