# Generated by Django 5.1.2 on 2026-03-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_add_intended_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_platform_owner',
            field=models.BooleanField(default=False, help_text='Platform owner tenant — permanent pro plan, no subscription required'),
        ),
    ]
