# Generated by Django 5.1.2 on 2026-03-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_set_rockstar_platform_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Connect Account ID (acct_...) for receiving invoice payments', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Customer ID for platform billing', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Subscription ID for platform billing', max_length=50),
        ),
    ]
