# Generated by Django 5.1.2 on 2026-07-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_add_stripe_id_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='services_offered',
            field=models.CharField(choices=[('repair', 'Repairs only'), ('replacement', 'Replacements only'), ('both', 'Both repairs and replacements')], default='both', help_text='Which services this shop performs', max_length=20),
        ),
    ]
