# Generated by Django 5.1.2 on 2026-07-19 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_tenant_services_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='brand_color',
            field=models.CharField(blank=True, default='', help_text="Shop's brand color, used on invoices, emails, and the customer portal. Blank = platform default.", max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a hex color like #3b82f6.')]),
        ),
    ]
