# Generated by Django 5.1.2 on 2026-08-06 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_fix_stripe_price_ids_wrong_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_step', models.PositiveSmallIntegerField(default=0)),
                ('wizard_completed_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('trial_banner_dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('tours_completed', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Onboarding State',
                'verbose_name_plural': 'Onboarding States',
            },
        ),
    ]
