# Generated by Django 5.1.2 on 2026-08-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_onboardingstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_synced_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the newest Stripe event applied to this tenant's subscription state. Older events are ignored.", null=True),
        ),
    ]
