# Generated by Django 5.1.2 on 2026-08-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_tenant_subscription_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='past_due_since',
            field=models.DateTimeField(blank=True, help_text='When this tenant first went past_due. Cleared on recovery.', null=True),
        ),
    ]
