# Generated by Django 5.1.2 on 2026-08-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_tenant_past_due_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='platform_fee_fixed_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Override the global fixed fee component, in cents. Resolved as a unit with platform_fee_percent: setting either one makes this tenant use its own pair, treating the unset half as 0.', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='platform_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override global platform fee % for this tenant. Null = use global default.', max_digits=5, null=True),
        ),
    ]
