# Generated by Django 5.1.2 on 2026-08-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_backfill_platform_fee_percent_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='trialing', help_text='Current subscription lifecycle status', max_length=20),
        ),
    ]
