# Generated by Django 5.1.2 on 2025-12-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0017_technician_email_verified_technician_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When email address was verified', null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='When phone number was verified', null=True),
        ),
    ]
