# Generated by Django 5.1.2 on 2026-01-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0018_technician_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='resin_viscosity',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
