# Generated by Django 5.1.2 on 2026-01-28 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_expand_data_model'),
        ('technician_portal', '0019_create_invoice_payment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='adas_calibration_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost for ADAS recalibration if required', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='authorization_number',
            field=models.CharField(blank=True, help_text='Insurance authorization/approval number', max_length=50),
        ),
        migrations.AddField(
            model_name='repair',
            name='claim_number',
            field=models.CharField(blank=True, help_text='Insurance claim number', max_length=50),
        ),
        migrations.AddField(
            model_name='repair',
            name='deductible',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Customer's deductible amount", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='glass_position',
            field=models.CharField(blank=True, choices=[('WINDSHIELD', 'Windshield'), ('FRONT_LEFT', 'Front Left Window'), ('FRONT_RIGHT', 'Front Right Window'), ('REAR_LEFT', 'Rear Left Window'), ('REAR_RIGHT', 'Rear Right Window'), ('REAR', 'Rear Window'), ('QUARTER_LEFT', 'Left Quarter Glass'), ('QUARTER_RIGHT', 'Right Quarter Glass'), ('SUNROOF', 'Sunroof / Moonroof'), ('OTHER', 'Other')], help_text='Which glass is being replaced (windshield, side, rear, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='repair',
            name='glass_type',
            field=models.CharField(blank=True, choices=[('OEM', 'OEM'), ('AFTERMARKET', 'Aftermarket'), ('', 'Not specified')], help_text='OEM = original manufacturer glass. Aftermarket = third-party.', max_length=15),
        ),
        migrations.AddField(
            model_name='repair',
            name='insurance_claim',
            field=models.BooleanField(default=False, help_text='Is this an insurance claim?'),
        ),
        migrations.AddField(
            model_name='repair',
            name='insurance_company',
            field=models.CharField(blank=True, help_text='Insurance company name', max_length=100),
        ),
        migrations.AddField(
            model_name='repair',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Labor cost for replacement', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='nags_number',
            field=models.CharField(blank=True, help_text='NAGS part number for the glass (industry standard identifier)', max_length=20),
        ),
        migrations.AddField(
            model_name='repair',
            name='parts_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of replacement glass and materials', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='requires_adas_calibration',
            field=models.BooleanField(default=False, help_text='Does this replacement require ADAS sensor recalibration?'),
        ),
        migrations.AddField(
            model_name='repair',
            name='service_type',
            field=models.CharField(choices=[('REPAIR', 'Windshield Repair'), ('REPLACEMENT', 'Glass Replacement')], db_index=True, default='REPAIR', help_text='Repair = chip/crack fix. Replacement = full glass swap.', max_length=15),
        ),
        migrations.AddField(
            model_name='repair',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Link to vehicle record (optional — unit_number still works for fleets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs', to='core.vehicle'),
        ),
    ]
