# Generated by Django 5.1.2 on 2026-01-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0022_remove_replacement_fields_from_repair'),
        ('tenants', '0001_create_tenant_and_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repair',
            options={'ordering': ['-service_date'], 'verbose_name': 'Repair', 'verbose_name_plural': 'Repairs'},
        ),
        migrations.AlterModelOptions(
            name='replacement',
            options={'ordering': ['-service_date'], 'verbose_name': 'Replacement', 'verbose_name_plural': 'Replacements'},
        ),
        migrations.AlterModelOptions(
            name='techniciannotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Technician Notification', 'verbose_name_plural': 'Technician Notifications'},
        ),
        migrations.AlterModelOptions(
            name='unitrepaircount',
            options={'verbose_name': 'Unit Repair Count', 'verbose_name_plural': 'Unit Repair Counts'},
        ),
        migrations.AddField(
            model_name='repair',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='replacement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='technician',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='unitrepaircount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_repair_counts', to='tenants.tenant'),
        ),
    ]
