# Generated by Django 5.1.2 on 2026-01-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0023_add_tenant_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='can_repair',
            field=models.BooleanField(default=True, help_text='Can perform chip/crack repairs'),
        ),
        migrations.AddField(
            model_name='technician',
            name='can_replace',
            field=models.BooleanField(default=False, help_text='Can perform glass replacements'),
        ),
    ]
