# Generated by Django 5.1.2 on 2026-01-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customer_email_alter_customer_name_and_more'),
        ('technician_portal', '0024_add_technician_abilities'),
        ('tenants', '0006_add_assignment_strategy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unitrepaircount',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='unitrepaircount',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer', 'unit_number'), name='unique_unit_repair_count_per_tenant'),
        ),
    ]
