# Generated by Django 5.1.2 on 2026-01-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0025_alter_unitrepaircount_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='managed_technicians',
            field=models.ManyToManyField(blank=True, help_text='Technicians managed by this manager (must be same tenant)', related_name='managers', to='technician_portal.technician'),
        ),
    ]
