# Generated by Django 5.1.2 on 2026-02-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0027_add_tax_fields_to_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='vehicle_make',
            field=models.CharField(blank=True, help_text='Vehicle make (e.g., Ford, Toyota, Chevrolet)', max_length=50),
        ),
        migrations.AddField(
            model_name='repair',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='Vehicle model (e.g., F-150, Camry, Silverado)', max_length=50),
        ),
        migrations.AddField(
            model_name='repair',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, help_text='Vehicle year (e.g., 2019)', null=True),
        ),
        migrations.AddField(
            model_name='replacement',
            name='vehicle_make',
            field=models.CharField(blank=True, help_text='Vehicle make (e.g., Ford, Toyota, Chevrolet)', max_length=50),
        ),
        migrations.AddField(
            model_name='replacement',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='Vehicle model (e.g., F-150, Camry, Silverado)', max_length=50),
        ),
        migrations.AddField(
            model_name='replacement',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, help_text='Vehicle year (e.g., 2019)', null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
