# Generated by Django 5.1.2 on 2026-02-17 22:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0029_add_skip_invoicing_to_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='replacement',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Tax rate applied to this replacement (percentage, e.g. 6.500 = 6.5%)', max_digits=5),
        ),
    ]
