# Generated by Django 5.1.2 on 2026-02-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0030_add_tax_fields_to_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='damage_location_x',
            field=models.FloatField(blank=True, help_text='X coordinate of damage on windshield (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='damage_location_y',
            field=models.FloatField(blank=True, help_text='Y coordinate of damage on windshield (0-100%)', null=True),
        ),
    ]
