# Generated by Django 5.1.2 on 2026-03-07 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0031_add_damage_location'),
        ('tenants', '0009_add_pricing_tiers_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='viscosityrecommendation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viscosity_recommendations', to='tenants.tenant'),
        ),
    ]
