# Generated by Django 5.1.2 on 2026-03-07 22:11

from django.db import migrations


def backfill_viscosity_tenant(apps, schema_editor):
    """Assign existing ViscosityRecommendation records to the default tenant."""
    Tenant = apps.get_model('tenants', 'Tenant')
    ViscosityRecommendation = apps.get_model('technician_portal', 'ViscosityRecommendation')

    default_tenant = Tenant.objects.first()
    if default_tenant:
        ViscosityRecommendation.objects.filter(tenant__isnull=True).update(tenant=default_tenant)


def reverse_backfill(apps, schema_editor):
    """Remove tenant assignment (set to null)."""
    ViscosityRecommendation = apps.get_model('technician_portal', 'ViscosityRecommendation')
    ViscosityRecommendation.objects.all().update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0032_add_tenant_to_viscosity_recommendation'),
        ('tenants', '0009_add_pricing_tiers_to_tenant'),
    ]

    operations = [
        migrations.RunPython(backfill_viscosity_tenant, reverse_backfill),
    ]
