# Generated by Django 5.1.2 on 2026-03-25 12:04

from django.db import migrations


def seed_default_warranty_policies(apps, schema_editor):
    """
    For each existing tenant, create a default 'Standard Warranty' policy
    (365 days, all_repairs, is_default=True) if one doesn't already exist.
    """
    Tenant = apps.get_model('tenants', 'Tenant')
    WarrantyPolicy = apps.get_model('technician_portal', 'WarrantyPolicy')

    for tenant in Tenant.objects.all():
        if not WarrantyPolicy.objects.filter(tenant=tenant, is_default=True).exists():
            WarrantyPolicy.objects.create(
                tenant=tenant,
                name='Standard Warranty',
                applies_to='all_repairs',
                duration_type='custom_days',
                duration_days=365,
                coverage_description=(
                    'One year warranty on all repairs against defects '
                    'in workmanship.'
                ),
                covers_labor=True,
                covers_materials=True,
                is_default=True,
                is_active=True,
            )


def reverse_seed(apps, schema_editor):
    """Remove seeded policies (only ones matching the exact seed name)."""
    WarrantyPolicy = apps.get_model('technician_portal', 'WarrantyPolicy')
    WarrantyPolicy.objects.filter(
        name='Standard Warranty',
        is_default=True,
        applies_to='all_repairs',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0036_add_warranty_policy_and_repair_warranty_fields'),
    ]

    operations = [
        migrations.RunPython(seed_default_warranty_policies, reverse_seed),
    ]
