# Generated by Django 5.1.2 on 2026-03-27 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_relax_phone_validation'),
        ('technician_portal', '0037_seed_default_warranty_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='is_goodwill_repair',
            field=models.BooleanField(default=False, help_text='Courtesy repair outside warranty — excluded from loyalty points'),
        ),
        migrations.AddField(
            model_name='repair',
            name='is_warranty_claim',
            field=models.BooleanField(default=False, help_text='This repair is a warranty claim against an original repair'),
        ),
        migrations.AddField(
            model_name='repair',
            name='warranty_original_repair',
            field=models.ForeignKey(blank=True, help_text='Original repair this warranty claim is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claims', to='technician_portal.repair'),
        ),
        migrations.AddField(
            model_name='warrantypolicy',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='If set, this policy applies only to this customer (fleet override).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_policies', to='core.customer'),
        ),
    ]
