# Generated by Django 5.1.2 on 2026-03-27 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_relax_phone_validation'),
        ('customer_portal', '0012_add_review_opt_out_to_customeruser'),
        ('technician_portal', '0038_warranty_phase2_fields'),
        ('tenants', '0017_add_stripe_id_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable automated review requests after completed repairs.')),
                ('google_review_url', models.URLField(blank=True, help_text='Direct Google review URL (e.g. from Google Business dashboard).')),
                ('email_subject', models.CharField(default='How was your experience with {shop_name}?', max_length=200)),
                ('email_body_template', models.TextField(blank=True, help_text='Custom message body. Leave blank for default template.')),
                ('retail_cooldown_days', models.PositiveIntegerField(default=90, help_text='Min days between review requests for repeat retail customers.')),
                ('fleet_cooldown_days', models.PositiveIntegerField(default=180, help_text='Min days between review requests for fleet accounts.')),
                ('send_delay_hours', models.PositiveIntegerField(default=2, help_text='Hours after repair completion before sending review request.')),
                ('business_hours_start', models.PositiveIntegerField(default=9, help_text='Earliest hour (0-23) to send review requests.')),
                ('business_hours_end', models.PositiveIntegerField(default=19, help_text='Latest hour (0-23) to send review requests.')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Review Configuration',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('clicked', 'Clicked'), ('reviewed', 'Reviewed'), ('skipped', 'Skipped'), ('suppressed', 'Suppressed')], default='pending', max_length=20)),
                ('skip_reason', models.CharField(blank=True, max_length=100)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='core.customer')),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_requests', to='customer_portal.customeruser')),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_requests', to='technician_portal.repair')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'customer', '-created_at'], name='technician__tenant__a5e2e1_idx'), models.Index(fields=['status', 'scheduled_at'], name='technician__status_1cedb2_idx')],
            },
        ),
    ]
