# Generated by Django 5.1.2 on 2026-03-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0039_add_reviewconfig_reviewrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='queue_status',
            field=models.CharField(choices=[('REQUESTED', 'Customer Requested'), ('PENDING', 'Approval Pending'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DENIED', 'Denied by Customer')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='queue_status',
            field=models.CharField(choices=[('REQUESTED', 'Customer Requested'), ('PENDING', 'Approval Pending'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DENIED', 'Denied by Customer')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
