# Generated by Django 5.1.2 on 2026-07-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0040_add_queue_status_db_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='skip_invoicing',
            field=models.BooleanField(default=False, help_text='Skip this replacement when listing uninvoiced work (e.g., already paid outside system)'),
        ),
    ]
