# Generated by Django 5.1.2 on 2026-07-19 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0041_replacement_skip_invoicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='is_warranty_claim',
            field=models.BooleanField(default=False, help_text='This service is a warranty claim against an original service'),
        ),
        migrations.AddField(
            model_name='replacement',
            name='warranty_expires_at',
            field=models.DateTimeField(blank=True, help_text='Warranty expiration. Null with a policy = lifetime warranty.', null=True),
        ),
        migrations.AddField(
            model_name='replacement',
            name='warranty_policy',
            field=models.ForeignKey(blank=True, help_text='Warranty policy applied to this service on completion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='technician_portal.warrantypolicy'),
        ),
        migrations.AddField(
            model_name='replacement',
            name='warranty_void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replacement',
            name='warranty_void_reason',
            field=models.CharField(blank=True, help_text='Reason warranty was voided (e.g. new impact damage)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='is_warranty_claim',
            field=models.BooleanField(default=False, help_text='This service is a warranty claim against an original service'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='warranty_policy',
            field=models.ForeignKey(blank=True, help_text='Warranty policy applied to this service on completion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='technician_portal.warrantypolicy'),
        ),
        migrations.AlterField(
            model_name='warrantypolicy',
            name='applies_to',
            field=models.CharField(choices=[('repairs', 'Repairs'), ('replacements', 'Replacements')], default='repairs', max_length=30),
        ),
    ]
