# Generated by Django 5.1.2 on 2026-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0045_repair_no_tax_replacement_no_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When set, this replacement is soft-deleted and excluded from normal querysets', null=True),
        ),
    ]
