# Generated by Django 5.1.2 on 2026-07-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0046_replacement_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewconfig',
            name='send_to_fleet',
            field=models.BooleanField(default=False, help_text='Also send review requests to fleet accounts. Off by default — requests go only to individual (retail / walk-in) customers.'),
        ),
    ]
