# Generated by Django 5.1.2 on 2026-08-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technician_portal", "0047_reviewconfig_send_to_fleet"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewconfig",
            name="send_via_email",
            field=models.BooleanField(
                default=True, help_text="Send review requests by email."
            ),
        ),
        migrations.AddField(
            model_name="reviewconfig",
            name="send_via_sms",
            field=models.BooleanField(
                default=False, help_text="Send review requests by text message (SMS)."
            ),
        ),
        migrations.AddField(
            model_name="reviewconfig",
            name="sms_body_template",
            field=models.CharField(
                blank=True,
                help_text="Custom SMS text (review link is added automatically). Leave blank for default. Placeholders: {shop_name}, {customer_name}.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="sent_via",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
