# Generated by Django 5.1.2 on 2026-08-03 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0047_reviewconfig_send_to_fleet'),
        ('tenants', '0021_fix_stripe_price_ids_wrong_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_presets', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Fee Preset',
                'verbose_name_plural': 'Fee Presets',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_charges', to='technician_portal.repair')),
                ('replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_charges', to='technician_portal.replacement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_charges', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Job Charge',
                'verbose_name_plural': 'Job Charges',
                'ordering': ['id'],
            },
        ),
    ]
