# Generated by Django 5.1.2 on 2026-08-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0048_feepreset_jobcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewconfig',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Send review requests by text when the customer has agreed to texts.'),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'Text message')], default='email', help_text='How this request goes out (chosen at scheduling time).', max_length=8),
        ),
    ]
