# Generated by Django 5.1.2 on 2026-08-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0049_repair_internal_notes_replacement_internal_notes_and_more'),
        ('technician_portal', '0049_reviewconfig_sms_enabled_reviewrequest_channel'),
    ]

    operations = [
    ]
