# Generated by Django 5.1.2 on 2026-08-14 18:04

import common.encryption
import django.db.models.deletion
import rs_systems.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0051_rekey_individual_unit_repair_counts'),
        ('tenants', '0027_alter_tenant_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MygrantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.CharField(blank=True, help_text='Mygrant Customer ID (e.g. C000001-001).', max_length=20)),
                ('web_user_id', models.CharField(blank=True, help_text='MygrantGlass.com web user ID.', max_length=100)),
                ('password', common.encryption.EncryptedTextField(blank=True, default='', help_text='MygrantGlass.com password. Encrypted at rest.')),
                ('api_key', common.encryption.EncryptedTextField(blank=True, default='', help_text='Mygrant API key. Encrypted at rest.')),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='When Test connection last succeeded.', null=True)),
                ('last_verify_error', models.CharField(blank=True, help_text='Why the last Test connection failed (empty = last test passed).', max_length=255)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Mygrant Configuration',
                'abstract': False,
            },
            bases=(rs_systems.model_mixins.AutoUpdateTimestampMixin, models.Model),
        ),
    ]
