# Generated by Django 5.1.2 on 2026-08-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_customer_sms_opt_in_source'),
        ('technician_portal', '0052_mygrantconfig'),
        ('tenants', '0027_alter_tenant_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='When the shop promised to do this job. Blank = unscheduled.', null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='scheduled_window_end',
            field=models.DateTimeField(blank=True, help_text='Optional end of the promised arrival window.', null=True),
        ),
        migrations.AddField(
            model_name='replacement',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='When the shop promised to do this job. Blank = unscheduled.', null=True),
        ),
        migrations.AddField(
            model_name='replacement',
            name='scheduled_window_end',
            field=models.DateTimeField(blank=True, help_text='Optional end of the promised arrival window.', null=True),
        ),
        migrations.AddIndex(
            model_name='repair',
            index=models.Index(fields=['scheduled_for'], name='technician__schedul_920ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='replacement',
            index=models.Index(fields=['scheduled_for'], name='technician__schedul_5ac18f_idx'),
        ),
    ]
