# Generated by Django 5.1.2 on 2026-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0053_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='service_address',
            field=models.TextField(blank=True, default='', help_text="Street address where the vehicle is. Blank = customer's address."),
        ),
        migrations.AddField(
            model_name='repair',
            name='service_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repair',
            name='service_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repair',
            name='service_zip',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='replacement',
            name='service_address',
            field=models.TextField(blank=True, default='', help_text="Street address where the vehicle is. Blank = customer's address."),
        ),
        migrations.AddField(
            model_name='replacement',
            name='service_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='replacement',
            name='service_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='replacement',
            name='service_zip',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
