# Generated by Django 5.1.2 on 2026-08-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0057_repairphotocrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairphotocrop',
            name='confirmed_by_human',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repairphotocrop',
            name='suggested_by',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='repairphotocrop',
            name='suggested_x_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairphotocrop',
            name='suggested_y_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairphotocrop',
            name='suggestion_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
