# Generated by Django 5.1.2 on 2026-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0059_backfill_confirmed_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='needs_assignment',
            field=models.BooleanField(db_index=True, default=False, help_text="Nobody has deliberately picked a technician for this job yet. `technician` is NOT NULL, so a strategy that declines to assign (Manual, or Primary Tech First with no primary tech) leaves the caller's provisional pick on the row and raises this flag instead. It is what the Unassigned queue lists, and why the provisional tech is not notified."),
        ),
        migrations.AddField(
            model_name='replacement',
            name='needs_assignment',
            field=models.BooleanField(db_index=True, default=False, help_text="Nobody has deliberately picked a technician for this job yet. `technician` is NOT NULL, so a strategy that declines to assign (Manual, or Primary Tech First with no primary tech) leaves the caller's provisional pick on the row and raises this flag instead. It is what the Unassigned queue lists, and why the provisional tech is not notified."),
        ),
    ]
