# Generated by Django 5.1.2 on 2026-08-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0060_add_needs_assignment'),
        ('technician_portal', '0060_photocrop_replacement_fk'),
    ]

    operations = [
    ]
