# Generated by Django 5.1.2 on 2026-09-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_quotes'),
        ('technician_portal', '0061_merge_needs_assignment_and_photocrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='billing.quote'),
        ),
        migrations.AddField(
            model_name='replacement',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='billing.quote'),
        ),
    ]
