# Generated by Django 5.1.2 on 2026-09-16 23:41

import django.db.models.deletion
import rs_systems.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0062_quotes'),
        ('tenants', '0027_alter_tenant_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('make_key', models.CharField(db_index=True, editable=False, max_length=50)),
                ('model_key', models.CharField(db_index=True, editable=False, max_length=50)),
                ('vehicle_year', models.PositiveIntegerField(default=0)),
                ('glass_position', models.CharField(blank=True, default='', max_length=20)),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adas_calibration_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('LEARNED', 'Learned from a completed job'), ('PINNED', 'Set by the shop'), ('QUOTE', 'Supplier quote')], default='LEARNED', max_length=10)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_book_entries', to='technician_portal.replacement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_book_entries', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'price book entry',
                'verbose_name_plural': 'price book entries',
                'ordering': ['make_key', 'model_key', 'vehicle_year', 'glass_position'],
                'indexes': [models.Index(fields=['tenant', 'make_key', 'model_key'], name='price_book_vehicle_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'make_key', 'model_key', 'vehicle_year', 'glass_position'), name='price_book_one_row_per_vehicle_glass')],
            },
            bases=(rs_systems.model_mixins.AutoUpdateTimestampMixin, models.Model),
        ),
    ]
