# Generated by Django 5.1.2 on 2026-08-06 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        ('tenants', '0022_onboardingstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(help_text='Where the reply goes', max_length=254)),
                ('topic', models.CharField(choices=[('question', 'How do I do something?'), ('problem', "Something's not working"), ('billing', 'Billing & my plan'), ('idea', 'I have an idea'), ('other', 'Something else')], default='question', max_length=20)),
                ('message', models.TextField()),
                ('page', models.CharField(blank=True, help_text='Page the sender was on before opening the form', max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('emailed_ok', models.BooleanField(default=False, help_text='Whether the notification email to the admins was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
