# Generated by Django 5.1.2 on 2026-09-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='shop_name',
            field=models.CharField(blank=True, help_text="Shop the sender named, when they weren't logged in", max_length=150),
        ),
    ]
