# Generated by Django 5.1.2 on 2026-09-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='acknowledged',
            field=models.BooleanField(default=False, help_text='Whether the sender got the "we got your message" email'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='role',
            field=models.CharField(blank=True, help_text="The sender's role in their shop at the time (owner/manager/technician), if signed in", max_length=20),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='source',
            field=models.CharField(choices=[('app', 'Signed-in (/help/contact/)'), ('public', 'Public (/contact/)'), ('portal', 'Customer portal')], db_index=True, default='app', max_length=10),
        ),
    ]
