# Generated by Django 5.1.2 on 2026-09-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportmessage_source_role_ack'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidefeedback',
            name='reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
