# Generated by Django 5.1.2 on 2026-01-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_alter_customerrepairpreference_units_per_visit_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrepairpreference',
            name='auto_email_invoices',
            field=models.BooleanField(default=False, help_text='Automatically email invoices when generated?'),
        ),
        migrations.AddField(
            model_name='customerrepairpreference',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Email for invoices (uses customer email if blank)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customerrepairpreference',
            name='include_photos_in_invoice',
            field=models.BooleanField(default=True, help_text='Include repair photos in invoice emails?'),
        ),
        migrations.AddField(
            model_name='customerrepairpreference',
            name='invoice_preference',
            field=models.CharField(choices=[('per_ticket', 'Invoice per repair (auto-generate when completed)'), ('batch', 'Batch invoicing (group repairs together)'), ('manual', 'Manual only (never auto-generate)')], default='batch', help_text='How should invoices be generated for this customer?', max_length=20),
        ),
    ]
