# Generated by Django 5.1.2 on 2026-01-29 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0007_add_invoice_preferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerpreference',
            options={'verbose_name': 'Customer Preference', 'verbose_name_plural': 'Customer Preferences'},
        ),
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'Customer User', 'verbose_name_plural': 'Customer Users'},
        ),
    ]
