# Generated by Django 5.1.2 on 2026-02-25 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0009_add_customer_invitation'),
        ('technician_portal', '0031_add_damage_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('deny', 'Deny')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tokens', to='customer_portal.customeruser')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tokens', to='technician_portal.repair')),
            ],
            options={
                'verbose_name': 'Approval Token',
                'verbose_name_plural': 'Approval Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
