# Generated by Django 5.1.2 on 2026-03-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0011_customerinvitation_is_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='review_opt_out',
            field=models.BooleanField(default=False, help_text='If True, this user will never receive review request emails.'),
        ),
    ]
