# Generated by Django 5.1.2 on 2026-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0015_default_existing_prefs_to_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When set, this portal user was removed and their login deactivated', null=True),
        ),
    ]
